apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: kafka-elk
data:
  elasticsearch.yml: |
    # 기존 설정들
    xpack.security.enabled: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: kafka-elk
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
        ports:
        - containerPort: 9200
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-passwords
                key: elastic
      volumes:
      - name: config-volume
        configMap:
          name: elasticsearch-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: kafka-elk
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30920
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
      nodePort: 30930
  type: NodePort
