apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: kafka-elk
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["https://211.183.3.198:30920"]
    elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL2RlZmF1bHQ6RHFjeWhFMzBTaXlQYnA4dG9hU2xRQQ"
    elasticsearch.ssl.verificationMode: "none"
    xpack.security.encryptionKey: "eFafloJUczIDd8eZT4a38X+Msl0XNPIw3oXctWdkuJk="
    xpack.encryptedSavedObjects.encryptionKey: "ndLietr9R1lccl1WWLJMSTveG60eV4Fx5AVzZxyzyKs="
    server.ssl.enabled: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kafka-elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.10.1
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kafka-elk
spec:
  selector:
    app: kibana
  ports:
  - protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30081
  type: NodePort
